# Generated by Django 5.1.3 on 2026-03-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
