# Generated by Django 5.1.3 on 2026-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="position",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
