# Generated by Django 5.1.3 on 2026-03-18 23:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_election_slug_position_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="politicalparty",
            name="badge",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="badge"
            ),
        ),
    ]
